name: "Commit Lint"

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  pull-requests: read
  contents: read

jobs:
  commitlint:
    name: "Commit Lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
